# cbox: src/Makefile
# Written by littlefly365 (cristianherrera26)
# Last change: 12-08-2026

PROG=	cbox
SRCS=	basename.c dirname.c echo.c false.c libbox.c main.c logname.c pwd.c true.c whoami.c yes.c
NOMAN=

CFLAGS=-Oz

.include <bsd.prog.mk>
